/* eslint-disable no-unused-vars */
import * as bootstrap from 'bootstrap';
import './scss/base.scss';
import './scss/homepage.scss';
import './scss/contact.scss';
import './scss/header.scss';
import './scss/heroNavigation.scss';
import './scss/footer.scss';
import './modules/loaderAnimation.js';
import './modules/swiper/servicesSwiper.js';
import './modules/swiper/resultsSwiper.js';
import './modules/swiper/testimonialSwiper.js';
import './modules/headerMenu.js';
import './modules/footerAnimation.js';
import './modules/scrollHeader.js';
import './modules/heroPopUp.js';
import './modules/heroNavigationIconAnimation.js';
import './modules/bodyBackgroundAnimation.js';
import './modules/digitalMarketingAnimation.js';
import './modules/gritCaseStudyAnimation.js';
import './modules/percentageAnimation.js';
